
security:
     oauth2:
         client:
             clientId: 3973707286079514
             clientSecret: 1a76580387141cbea64717009c452d56
             accessTokenUri: https://graph.facebook.com/oauth/access_token
             userAuthorizationUri: https://www.facebbook.com/dialog/oauth
             tokenName: oauth_token
             authenticationScheme: query
             clientAuthenticationScheme: form
         resource:
             userInfoUri: https://graph.facebook.com/me



server:
    port: 9095
spring:
    datasource:
        password: absek
        url: jdbc:mysql://localhost:3307/coding_challenge
        username: root
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: true

